### ISSUE TITLE
casinocoin-dev-portal/content/code_samples/casinocoinapi_quickstart/get-account-info.js

### ISSUE THREAD

**Issue by toastedcoins** [casinocoin/casinocoin-dev-portal#10]
Refers to Ripple server and address

  server: 'wss://s1.ripple.com' // Public rippled server
});
api.connect().then(() => {
  /* begin custom code ------------------------------------ */
  const myAddress = 'rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn';

**Comment by blocksninja** [comment]
this was already changed and live in the public web. Only repo was behind;
