### ISSUE TITLE
casinocoin-dev-portal/content/code_samples/casinocoinapi_quickstart/browser-demo.html

### ISSUE THREAD

**Issue by toastedcoins** [casinocoin/casinocoin-dev-portal#11]
Refers to Ripple Server

    var api = new ripple.RippleAPI({server:'wss://s1.ripple.com/'});
    api.connect().then(function() {
        return api.getServerInfo();
    }).then(function(server_info) {
    document.body.innerHTML += "<p>Connected to rippled server!</p>" +

**Comment by blocksninja** [comment]
thanks. This was already changed, repo is behind;
