### ISSUE TITLE
casinocoin-dev-portal/content/code_samples/freeze/set-no-freeze.js

### ISSUE THREAD

**Issue by toastedcoins** [casinocoin/casinocoin-dev-portal#12]
Ripple Server and addresses

  server: 'wss://s1.ripple.com' // Public rippled server
});
api.on('error', (errorCode, errorMessage) => {
  console.log(errorCode + ': ' + errorMessage);
});

const issuing_address = 'rUpy3eEg8rqjqfUoLeBnZkscbKbFsKXC3v';
const issuing_secret = 'snnDVkSW3aV6jvMJTPdCiE2Qxv1RW';
    // Best practice: get your secret from an encrypted
    //  config file instead

**Comment by blocksninja** [comment]
changed;
