### ISSUE TITLE
casinocoin-dev-portal/content/reference-data-api.md

### ISSUE THREAD

**Issue by Marec4** [casinocoin/casinocoin-dev-portal#13]
rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B
r2d2iZiCcJmNL6vhUGFjs8U8BuUq6BnmT
rfCFLzNJYvvnoGHWQYACmJpTgkLUaugLEw
rfYqosNivHQFJ6KpArouxoci3QE3huKNYe
rJ6VE6L87yaVmdyxa9jZFXSAdEFSoTGPbE
rB5TihdPbKgMrkFqrqUC3yLdE8hhv4BdeY
rfitr7nL7MX85LLKJce7E3ATQjSiyUPDfj
rhdAw3LiEfWWmSrbnZG3udsN7PoWKT56Qo
rfitr7nL7MX85LLKJce7E3ATQjSiyUPDfj
rhdAw3LiEfWWmSrbnZG3udsN7PoWKT56Qo
rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q
rwm98fCBS8tV1YB8CGho8zUPW5J7N41th2
rpP2JgiMyTF5jR5hLG3xHCPi1knBb1v9cM
rK2o63evRPdRoMT2ZaW72wsHsFzcjnRLLq
rfh3pFHkCXv3TgzsEJgyCzF1CduZHCLi9o
rpP2JgiMyTF5jR5hLG3xHCPi1knBb1v9cM
r2nt4zXDP6Be5FNrLsiuuTEBETbGR9RFw
r2LXq2rZWSgQ1thhKiEytzi1smg6oEn8A
rDMFJrKg2jyoNG6WDWJknXDEKZ6ywNFGwD
r4XXHxraHLuCiLmLMw96FTPXXywZSnWSyR
rp1C4Ld6uGjurFpempUJ8q5hPSWhak5EQf
rwxcJVWZSEgN2DmLZYYjyagHjMx5jQ7BAa
rBK1rLjbWsSU9EuST1cAz9RsiYdJPVGXXA
r2adXWaWFJt9mHeoWN77iHJozDz2FDAPA
rB4cyZxrBrTmJcWZSBc8YoW2t3bafiKRp
rNRCXw8PQRjvTwMDDLZVvuLHSKqqXUXQHv
r7CLMVEuNvK2yXTPLPnkWMqzkkXuopWeL
ranyeoYRhvwiFABzDvxSVyqQKp1bMkFsaX
rGBQhB8EH5DmqMmfKPLchpqr3MR19pv6zN
rQE5Z3FgVnRMbVfS6xiVQFgB4J3X162FVD
rD8LigXE7165r3VWhSQ4FwzJy7PNrTMwUq
rfh3pFHkCXv3TgzsEJgyCzF1CduZHCLi9o
rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B
razqQKzJRdB4UxFPWf5NEpEG3WMkmwgcXA
r94s8px6kSw1uZ1MV98dhSRTvc6VMPoPcN
rG6FZ31hDHN1K5Dkbma3PSB5uVCuVVRzfn
rKiCet8SdvWxPXnAgYarFUXMh1zCPz432Y
rsP3mgGb2tcYUrxiLFiHJiQXhsziegtwBc
rrh7rf1gV2pXAoqA8oYbpHd8TKv5ZQeo67
rPxU6acYni7FcXzPCMeaPSwKcuS2GTtNVN
rUkMKjQitpgAM5WTGk79xpjT38DEJY283d
rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq
rhotcWYdfn6qxhVMbPKGDF3XCKqwXar5J4
raKEEVSGnKSD9Zyvxu4z6Pqpm4ABH8FS6n
rUpy3eEg8rqjqfUoLeBnZkscbKbFsKXC3v
rLFd1FzHMScFhLsXeaxStzv3UC97QHGAbM
ra5nK24KXen9AHvsdFTKHSANinZseWnPcX
rweYz56rfmQ98cAdRaeTxQS9wVMGnrdsFp
rK5j9n8baXfL4gzUoZsfxBvvsv97P5swaV
r94s8px6kSw1uZ1MV98dhSRTvc6VMPoPcN
rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq
rK5j9n8baXfL4gzUoZsfxBvvsv97P5swaV
rsyDrDi9Emy6vPU78qdxovmNpmj5Qh4NKw
rnAqwsu2BEbCjacoZmsXrpViqd3miZhHbT
rUkMKjQitpgAM5WTGk79xpjT38DEJY283d
r9xQi5YT8jqVM3wZhbiV94ZKKvGHaVeSDj
rhi4zZdCeFdfTokzek8D7p9bUWmtEFCZAe
rP1hkW1LCiVos6FpzU7itmm9Tk29yqvyk5
rGFuMiw48HdbnrUbkRYuitXTmfrDBNTCnX
rGFuMiw48HdbnrUbkRYuitXTmfrDBNTCnX

ripple.com
https://data.ripple.com
GET /v2/network/rippled_versions
rippled
ripple
rippled.media.mit.edu
git clone https://github.com/ripple/casinocoind-historical-database.git

**Comment by blocksninja** [comment]
changed;
