### ISSUE TITLE
casinocoin-dev-portal/assets/css/ripple.css

### ISSUE THREAD

**Issue by sureman123** [casinocoin/casinocoin-dev-portal#3]
line2 - ripple.com
line 5768 - ripple-beta
line 6004 - ripple
line 6013 - ripple_page_heading
line 6025 - ripple_page_heading
line 6128 - ripple_page_heading
line 6288 - page-ripple-deep-dive
line 6294 - page-ripple-deep-dive
line 6300 - Ripple logo font icon
line 6824 - ripple_footer

**Comment by blocksninja** [comment]
Thanks! Changed.
