### ISSUE TITLE
casinocoin-dev-portal/content/code_samples/casinocoinapi_quickstart/submit-and-verify.js

### ISSUE THREAD

**Issue by toastedcoins** [casinocoin/casinocoin-dev-portal#8]
Contains Ripple Addresses
rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn

rUpy3eEg8rqjqfUoLeBnZkscbKbFsKXC3v

Ripple Link 
wss://s2.ripple.com

**Comment by blocksninja** [comment]
changed;
